name: "优化提议 test"
description: "对已有功能的小幅度优化或改进建议"
labels: [优化, 等待初步确认]
body:
- type: textarea
  id: "ch-yml-2"
  attributes:
    label: 描述
    description: "详细描述优化提议的具体内容。"
  validations:
    required: true
- type: textarea
  id: "ch-yml-3"
  attributes:
    label: 原因
    description: "详细描述你为什么需要这项优化，这有助于开发者评估它的优先度。"
    value: |
      这项优化让我可以更方便地xxxx。
      如果没有这项优化，我每次都必须xxxx，让操作变得很麻烦。
  validations:
    required: true